### ISSUE TITLE
Bug:  使用 `database-mysql` 作为数据库实现时， 无法正常订阅

### ISSUE THREAD

**Issue by dingyi222666** [borraken/koishi-plugin-rss-owl#3]
如图：
![image](https://github.com/user-attachments/assets/263dc756-7dc4-4ee0-93cc-739c175b34a8)

猜测是因为如下原因引起的：

![image](https://github.com/user-attachments/assets/9adb9cff-d878-4b9d-adc4-db47bcad38f7)

https://github.com/borraken/koishi-plugin-rss-owl/blob/e3e8ad396835d5fa526083a28888715338fa5bf2/src/index.ts#L206

**Comment by dingyi222666** [comment]
你好，新版本仍然出现相关错误：

![2d03cab6397c3649d366bc8ac2bf34be](https://github.com/user-attachments/assets/963dad7e-fb69-4e42-bb80-f36f52924725)

建议在发布新版本前，使用 mysql 数据库进行测试。

**Comment by borraken** [comment]
4.7.1已发布，希望能解决你的问题
由于我这边没有配mysql环境，所以目前无法进行测试
如果还出现问题再看吧

**Comment by dingyi222666** [comment]
仍然不行：
![3594ebaab83e8bc78115a13cad08fb67](https://github.com/user-attachments/assets/60ba781f-33c1-487e-88c3-e3b9663ebb25)

参考 [Koishi 官方文档](https://koishi.chat/zh-CN/api/database/model.html)，如使用的字段类型是 `timestamp`，应该插入的是 `Date` 类型的数据。

**Comment by borraken** [comment]
4.7.2已发布，本地mysql测试已通过
