### ISSUE TITLE
[Feature Request] 希望能指定订阅发送的群

### ISSUE THREAD

**Issue by rainpenber** [borraken/koishi-plugin-rss-owl#4]
## 目前的情况
```text
rsso -i content tg:woshadiao
```
这条命令可以订阅tg内容并在当前群生效
但：
1. 我不希望在群里让群员看到我的指令内容
2. 我希望为不同的群添加不同的订阅内容

## 希望实现的效果
向群12345678添加一条订阅
```text
rsso -i content tg:woshadiao --target 12345678
```
在执行这条指令的地方提示：
> 向群12345678添加订阅 电报：woshadiao 成功！

在接受推送的群：不提示订阅成功的消息，但是正常接受每天的推送

效果参考：https://github.com/Colter23/bilibili-dynamic-mirai-plugin

**Comment by borraken** [comment]
4.7版本已更新
另外选项需要写在url的前面，否则会导致url解析错误
像这样
`rsso -i content --target 12345678 tg:woshadiao`
