### ISSUE TITLE
更新之后 无法推送了

### ISSUE THREAD

**Issue by cn1095** [borraken/koishi-plugin-rss-owl#5]
3:12:27 [I] rss-owl ReferenceError: description is not defined
                            at parseRssItem (/koishi/node_modules/koishi-plugin-rss-owl/lib/index.js:422:2)
                            at /koishi/node_modules/koishi-plugin-rss-owl/lib/index.js:587:91
                            at Array.map (<anonymous>)

**Comment by cn1095** [comment]
刚刚重新更新了4.7.0  可以推送了 再试试看   不过推送过了的内容 后面修改了内容还是没有推送

**Comment by borraken** [comment]
需要推送修改后的内容，需要在基础设置中配置resendUpdataContent
如果你配置后还是没有推送更新后的内容，能否提供相关rss订阅给我

**Comment by cn1095** [comment]
resendUpdataContent配置了最新的   已发布过的修改了不会推送   但是有最新的发布会推送  

数据库如下 好像不会记录进去 为空的    只有第一个正常 记录进去了  其余的 无论重启koishi 还是重启插件 都不会记录进去 
![图片](https://github.com/user-attachments/assets/fdef5ce6-86d2-429a-b9bb-fe8455a2d4ba)
全是github相关的订阅commits.atom releases.atom  issueopen

**Comment by borraken** [comment]
这个issue先关了，后面如果还出现无法推送再开
4.7.5尝试修复resendUpdataContent的问题，如果还是不行再另外反馈
